=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/remiss.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified" 
           targetNamespace="urn:riv:clinicalprocess:requestworkflow:request" 
           xmlns="urn:riv:clinicalprocess:requestworkflow:request" 
           xmlns:gcda="AlschulerAssociates::GreenCDA" 
           xmlns:codes="urn:riv:clinicalprocess:requestworkflow:codes"
           attributeFormDefault="unqualified">
    <xs:import schemaLocation='green_ccd.xsd' namespace='AlschulerAssociates::GreenCDA' />
    <xs:import schemaLocation='codes.xsd' namespace='urn:riv:clinicalprocess:requestworkflow:codes' />
    
    <xs:element name="request" type="RequestType"/> <!-- Remiss -->
    <xs:element name="requestOutcome" type="RequestOutcomeType"/> <!-- Remissvar -->
    
    <xs:complexType name="RequestType">
        <xs:sequence>
            <xs:element name="requestId" type="gcda:ii"/>
            <xs:element name="typeOfRequest" type="codes:codeForRequestType"/>
            <xs:element name="versionTimeStamp" type="gcda:ts"/>
            <xs:element name="versionNumber" type="xs:int"/>
            <xs:element name="reasonForVersion" type="ReasonForVersionType" />
            
            <xs:element name="patient" type="PatientType"/>
            
            <xs:element name="author" type="AuthorType"/>
            <xs:element name="recipient" type="RecipientType"/>
            <xs:element name="participant" type="RecipientType" minOccurs="0"/>
            <xs:element name="intermediary" type="IntermediaryType" minOccurs="0"/>
            
            <xs:element name="additionalInformation" type="AdditionalInformationType" />
            <xs:element name="awarenessInformation" type="AwarenessInformationType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="questionFormulation" type="QuestionFormulationType" />             
        </xs:sequence>        
    </xs:complexType>

    <xs:complexType name="RequestOutcomeType">
        <xs:sequence>
            <xs:element name="requestId" type="gcda:ii"/> <!-- inFulfillmentOf -->
            <xs:element name="requestOutcomeId" type="gcda:ii"/>
            <xs:element name="typeOfRequestOutcome" type="codes:codeRequestOutcomeType"/>
            <xs:element name="versionTimeStamp" type="gcda:ts"/>
            <xs:element name="versionNumber" type="xs:int"/>            
            <xs:element name="author" type="AuthorType"/>
            <xs:element name="recipient" type="RecipientType"/>
            <xs:element name="participant" type="RecipientType" minOccurs="0"/>          
            <xs:element name="outcome" type="OutcomeType" />
        </xs:sequence>        
    </xs:complexType>
    
    <xs:complexType name="TelecomType">
        <xs:sequence>
            <xs:element name="typeOfTelecom" type="codes:codeForTelecomType" />
            <xs:element name="number" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ReasonForVersionType">
        <xs:sequence>
            <xs:element name="typeOfReason" type="codes:codeVersionReason" />
            <xs:element name="text" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="PatientType">
        <xs:sequence>
            <xs:element name="personId" type="gcda:ii"/>
            <xs:element name="address" type="AddressType" minOccurs="0"/> 
            <xs:element name="telecom" type="TelecomType" minOccurs="0" maxOccurs="2"/>
            <xs:element name="name" type="xs:string" minOccurs="0" />
            <xs:element name="gender" type="codes:codeForGenderType" minOccurs="0" />
            <xs:element name="dateOfBirth" type="gcda:ts" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="careOf" type="xs:string" minOccurs="0"/>
            <xs:element name="streetName1" type="xs:string"/>
            <xs:element name="streetName2" type="xs:string" minOccurs="0"/>
            <xs:element name="streetName3" type="xs:string" minOccurs="0"/>
            <xs:element name="postalCode" type="xs:string"/>
            <xs:element name="postalCity" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="AuthorType">
        <xs:sequence>
            <xs:element name="dateOfRequest" type="gcda:ts"/>
            <xs:element name="staff" type="StaffType" />            
            <xs:element name="typeOfStaff" type="codes:codeForProfession" minOccurs="0" />
            <xs:element name="staffOrganisation" type="OrganisationType" /> <!-- custodian -->            
            <xs:element name="staffOriginOrganisation" type="OrganisationType" minOccurs="0" /> <!-- representedOrganisation -->
            <xs:element name="legalAuthenticator" type="LegalAuthenticatorType" /> <!-- legalAuthenticator -->
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="IntermediaryType">
        <xs:sequence>
            <xs:element name="staff" type="StaffType" />            
            <xs:element name="typeOfStaff" type="codes:codeForProfession" minOccurs="0" />
            <xs:element name="staffOrganisation" type="OrganisationType" /> <!-- custodian -->            
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="RecipientType">
        <xs:sequence>
            <xs:element name="staff" type="StaffType" minOccurs="0" />
            <xs:element name="typeOfStaff" type="codes:codeForProfession" minOccurs="0" />
            <xs:element name="organisation" type="OrganisationType" />            
        </xs:sequence>
    </xs:complexType>
        
    <xs:complexType name="LegalAuthenticatorType">
        <xs:sequence>
            <xs:element name="timeOfSigning" type="gcda:ts" />
            <xs:element name="signature" type="StaffType" minOccurs="0"/> <!-- Tolkning att denna Ã¤r frivillig... -->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StaffType">
        <xs:sequence>
            <xs:element name="id" type="gcda:ii" />
            <xs:element name="name" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="OrganisationType">
        <xs:sequence>
            <xs:element name="careUnitId" type="gcda:ii"/>
            <xs:element name="careUnitName" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="AdditionalInformationType">
        <xs:sequence>
            <xs:element name="text" type="xs:string" minOccurs="0"/> <!-- Narrative block! -->
            <xs:element name="desiredDateForPerformance" type="DesiredDateForPerformanceType" minOccurs="0"/>
            <xs:element name="desiredRequestRecipient" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="administrativeInformation" type="xs:string" minOccurs="0" />
            <xs:element name="interpreterRequirement" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AwarenessInformationType">
        <xs:sequence>
            <xs:element name="text" type="xs:string" />
            <xs:element name="clinicalInformation" type="DescriptionType" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>    
        
    <xs:complexType name="QuestionFormulationType">
        <xs:sequence>
            <xs:element name="id" type="gcda:ii"/>
            <xs:element name="text" type="xs:string" />
            <xs:element name="desiredAction" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="clinicalInformation" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OutcomeType">
        <xs:sequence>
            <xs:element name="text" type="xs:string" />
            <xs:element name="clinicalInformation" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="accomplishedAction" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="DesiredDateForPerformanceType">
        <xs:attribute name="start">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\d+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="end">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\d+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType> 
    
    <xs:complexType name="DescriptionType">
        <xs:sequence>
            <xs:element name="id" type="gcda:ii"/>
            <xs:element name="condition" type="gcda:ii" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/testcase_05_requestOutcome.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- SLL eRemiss testcase 5 -->
<requestOutcome xmlns:gcda="AlschulerAssociates::GreenCDA" xmlns:gcdan="AlschulerAssociates::GreenCDA::Narrative" xmlns="urn:riv:clinicalprocess:requestworkflow:request"
                xsi:schemaLocation="urn:riv:clinicalprocess:requestworkflow:request remiss.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">     
    <requestId root="1.2.752.129.2.1.2.1" extension="testfall5"/>
    <requestOutcomeId root="1.2.752.129.2.1.2.1" extension="testfall4"/>
    <typeOfRequestOutcome code="SS" codeSystem="1.2.752.97.3.2.8.6"/>
    <versionTimeStamp value="201203011636"/>
    <versionNumber>1</versionNumber>
   
    <!-- <requestrolltyp code="RB" displayName="Remissbesvarare" codeSystem="1.2.752.97.3.2.8.4"/> -->
    <author>
        <dateOfRequest value="20120418"/>
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSA-id for RB"/>
            <name>Gustav Olebratt</name>
        </staff>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8" />
        <staffOrganisation>
            <careUnitId root="1.2.752.97.3.1.1" extension="HSAid"/>
            <careUnitName>Capio S:t Görans sjukhus, Ortopedmottagningen</careUnitName>
        </staffOrganisation>
        <legalAuthenticator>
            <timeOfSigning value="201204181233"/>
            <signature>
                <id root="1.2.752.129.2.1.4.1" extension="HSA-id for signer"/>
                <name>Gustav Olebratt</name>
            </signature>
        </legalAuthenticator>
    </author>
    
    <!-- <requestrolltyp code="SM" displayName="Svarsmottagare" codeSystem="1.2.752.97.3.2.8.4"/> -->
    <recipient>
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSA-id for SM"/>
            <name>Jonas Dahl</name>
        </staff>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8" />
        <organisation>
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Hässelby vårdcentral</careUnitName>
        </organisation>
    </recipient>

    <outcome>
        <text>Tack för remissen! 
            Pat har idag 18/4 genomgått artroskopi som visade medial meniskruptur samt främre korsbandsskada. En partiell meniskresektion gjordes vid ingreppet. Avseende korsbandsskadan är patienten ordinerad stabilitetsträning via sjukgymnast. Inget planerat återbesök.

            Hälsningar
            Gustav Olebratt
            Specialistläkare
        </text>
        <clinicalInformation>
            <id root="1.2.752.116.1.1.1.1.3" extension="S83.2M" />
        </clinicalInformation>
        <clinicalInformation>
            <id root="1.2.752.116.1.1.1.1.3" extension="S83.5R" />
        </clinicalInformation>
        <accomplishedAction>
            <id root="1.2.752.116.1.3.2.1.4" extension="NGA11"/>  
            <description>Artroskopi höger knä</description>
        </accomplishedAction>
        <accomplishedAction>
            <id root="1.2.752.116.1.3.2.1.4" extension="NGD11"/> 
            <description>Partiell resektion av menisk</description>
        </accomplishedAction>    
    </outcome>
</requestOutcome>

=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/testcase_04_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- SLL eRemiss testcase 4 -->
<request xmlns:gcda="AlschulerAssociates::GreenCDA" xmlns:gcdan="AlschulerAssociates::GreenCDA::Narrative" xmlns="urn:riv:clinicalprocess:requestworkflow:request"
         xsi:schemaLocation="urn:riv:clinicalprocess:requestworkflow:request remiss.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
             
    <requestId root="1.2.752.129.2.1.2.1" extension="testfall4"/>
    <typeOfRequest code="4" codeSystem="1.2.752.129.2.2.2.24"/>
    <versionTimeStamp value="201203151636"/>
    <versionNumber>1</versionNumber>
    
    <reasonForVersion>
        <typeOfReason code="NR" codeSystem="1.2.752.97.3.2.8.5" />
        <text>Ny remiss</text>
    </reasonForVersion>

    <!-- Patient -->
    <patient>
        <personId root="1.2.752.97.3.1.2" extension="197907179191"/>

        <address>
            <careOf>Mikkonen</careOf>
            <streetName1>Astrakangatan 14</streetName1>
            <streetName2>Uppgång C</streetName2>
            <streetName3>Lgh 0014</streetName3>
            <postalCode>165 65</postalCode>
            <postalCity>Hässelby</postalCity>
        </address>
        
        <telecom>
            <typeOfTelecom code="H" codeSystem="1.2.752.129.2.2.1.30"/>
            <number>+468123123</number>
        </telecom>
        <telecom>
            <typeOfTelecom code="MC" codeSystem="1.2.752.129.2.2.1.30"/>
            <number>+46706123123</number>
        </telecom>
        <!-- Efternamn/mellannamn/tilltalsnamn/förnamn -->
        <name>Testsson/Anders/Vårdtest/Vårdtest</name>
        <gender code="1" codeSystem="1.2.752.129.2.2.1.1"/>
        <dateOfBirth value="19790917"/>
    </patient>
    
    <author>
        <dateOfRequest value="20120315"/>
        
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSA-id for RT"/>
            <name>Jonas Dahl</name>     
        </staff>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8" />
        <staffOrganisation>
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Hässelby vårdcentral</careUnitName>
        </staffOrganisation>
        <legalAuthenticator>
            <timeOfSigning value="201203151233"/>            
            <signature>
                <id root="1.2.752.129.2.1.4.1" extension="HSA-id for signer"/>
                <name>Jonas Dahl</name>
            </signature>
        </legalAuthenticator>
    </author>
    
    <recipient>
        <organisation>     
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Capio S:t Görans sjukhus, Ortopedmottagningen</careUnitName>
        </organisation>
    </recipient>
    
    <additionalInformation>
        <desiredDateForPerformance start="20120415" end="20120831" />
        <desiredRequestRecipient>Specialistläkare inom ortopedi</desiredRequestRecipient>
        <administrativeInformation>Patienten är bortrest utomlands 2012-03-15 – 2012-04-14 och kan därför kallas tidigast 2012-04-15</administrativeInformation>
        <interpreterRequirement>Behöver finsk tolk.</interpreterRequirement>
    </additionalInformation>
    
    <awarenessInformation>
        <text>Har hepatit C.</text>
    </awarenessInformation>

    <questionFormulation>
        <id root="1.2.752.129.2.1.2.1" extension="4"/>
        <text>Meniskskada? Korsbandsskada?</text>
        <desiredAction>
            <id root="1.2.752.97.3.1.11" extension="NGA11"></id>
            <description>Artroskopi höger knä</description>
        </desiredAction>
        <clinicalInformation>
            <id root="1.2.752.129.2.1.2.1" extension="4"/>
            <condition root="1.2.752.116.1.1.1.1.3" extension="S83.6" />
            <description>33-årig blandmissbrukande man som ramlade omkring 1 februari i berusat tillstånd och på något sätt skadat höger knä. Ej sökt vård. Sedan dess har patienten haft intermittent svullnad av höger knä och låsningsfenomen. I status noteras måttlig hydrops, kraftig smärta vid meniskprovokationstest och misstänkt främre draglåda. Röntgenundersökning har inte visat något patologiskt. Har ej genomgått MR. Tacksam för bedömning och ställningstagande till artroskopi.

                Hälsningar
                Jonas Dahl
                Distriktsläkare
            </description>
            
        </clinicalInformation>
    </questionFormulation>
</request>
