=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/remiss.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified" 
           targetNamespace="urn:riv:clinicalprocess:requestworkflow:request" 
           xmlns="urn:riv:clinicalprocess:requestworkflow:request" 
           xmlns:gcda="AlschulerAssociates::GreenCDA" 
           xmlns:codes="urn:riv:clinicalprocess:requestworkflow:codes"
           attributeFormDefault="unqualified">
    <xs:import schemaLocation='green_ccd.xsd' namespace='AlschulerAssociates::GreenCDA' />
    <xs:import schemaLocation='codes.xsd' namespace='urn:riv:clinicalprocess:requestworkflow:codes' />
    
    <xs:element name="request" type="RequestType"/> <!-- Remiss -->
    <xs:element name="requestOutcome" type="RequestOutcomeType"/> <!-- Remissvar -->
    
    <xs:complexType name="RequestType">
        <xs:sequence>
            <xs:element name="requestId" type="gcda:ii"/>
            <xs:element name="typeOfRequest" type="codes:codeForRequestType"/>
            <xs:element name="versionTimeStamp" type="gcda:ts"/>
            <xs:element name="versionNumber" type="xs:int"/>
            <xs:element name="reasonForVersion" type="ReasonForVersionType" />
            
            <xs:element name="patient" type="PatientType"/>
            
            <xs:element name="author" type="AuthorType"/>
            <xs:element name="recipient" type="RecipientType"/>
            <xs:element name="participant" type="RecipientType" minOccurs="0"/>
            <xs:element name="intermediary" type="IntermediaryType" minOccurs="0"/>
            
            <xs:element name="additionalInformation" type="AdditionalInformationType" />
            <xs:element name="awarenessInformation" type="AwarenessInformationType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="questionFormulation" type="QuestionFormulationType" />             
        </xs:sequence>        
    </xs:complexType>

    <xs:complexType name="RequestOutcomeType">
        <xs:sequence>
            <xs:element name="requestId" type="gcda:ii"/> <!-- inFulfillmentOf -->
            <xs:element name="requestOutcomeId" type="gcda:ii"/>
            <xs:element name="typeOfRequestOutcome" type="codes:codeRequestOutcomeType"/>
            <xs:element name="versionTimeStamp" type="gcda:ts"/>
            <xs:element name="versionNumber" type="xs:int"/>            
            <xs:element name="author" type="AuthorType"/>
            <xs:element name="recipient" type="RecipientType"/>
            <xs:element name="participant" type="RecipientType" minOccurs="0"/>          
            <xs:element name="outcome" type="OutcomeType" />
        </xs:sequence>        
    </xs:complexType>
    
    <xs:complexType name="TelecomType">
        <xs:sequence>
            <xs:element name="typeOfTelecom" type="codes:codeForTelecomType" />
            <xs:element name="number" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ReasonForVersionType">
        <xs:sequence>
            <xs:element name="typeOfReason" type="codes:codeVersionReason" />
            <xs:element name="text" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="PatientType">
        <xs:sequence>
            <xs:element name="personId" type="gcda:ii"/>
            <xs:element name="address" type="AddressType" minOccurs="0"/> 
            <xs:element name="telecom" type="TelecomType" minOccurs="0" maxOccurs="2"/>
            <xs:element name="name" type="xs:string" minOccurs="0" />
            <xs:element name="gender" type="codes:codeForGenderType" minOccurs="0" />
            <xs:element name="dateOfBirth" type="gcda:ts" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="careOf" type="xs:string" minOccurs="0"/>
            <xs:element name="streetName1" type="xs:string"/>
            <xs:element name="streetName2" type="xs:string" minOccurs="0"/>
            <xs:element name="streetName3" type="xs:string" minOccurs="0"/>
            <xs:element name="postalCode" type="xs:string"/>
            <xs:element name="postalCity" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="AuthorType">
        <xs:sequence>
            <xs:element name="dateOfRequest" type="gcda:ts"/>
            <xs:element name="staff" type="StaffType" />            
            <xs:element name="typeOfStaff" type="codes:codeForProfession" minOccurs="0" />
            <xs:element name="staffOrganisation" type="OrganisationType" /> <!-- custodian -->            
            <xs:element name="staffOriginOrganisation" type="OrganisationType" minOccurs="0" /> <!-- representedOrganisation -->
            <xs:element name="legalAuthenticator" type="LegalAuthenticatorType" /> <!-- legalAuthenticator -->
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="IntermediaryType">
        <xs:sequence>
            <xs:element name="staff" type="StaffType" />            
            <xs:element name="typeOfStaff" type="codes:codeForProfession" minOccurs="0" />
            <xs:element name="staffOrganisation" type="OrganisationType" /> <!-- custodian -->            
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="RecipientType">
        <xs:sequence>
            <xs:element name="staff" type="StaffType" minOccurs="0" />
            <xs:element name="typeOfStaff" type="codes:codeForProfession" minOccurs="0" />
            <xs:element name="organisation" type="OrganisationType" />            
        </xs:sequence>
    </xs:complexType>
        
    <xs:complexType name="LegalAuthenticatorType">
        <xs:sequence>
            <xs:element name="timeOfSigning" type="gcda:ts" />
            <xs:element name="signature" type="StaffType" minOccurs="0"/> <!-- Tolkning att denna Ã¤r frivillig... -->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StaffType">
        <xs:sequence>
            <xs:element name="id" type="gcda:ii" />
            <xs:element name="name" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="OrganisationType">
        <xs:sequence>
            <xs:element name="careUnitId" type="gcda:ii"/>
            <xs:element name="careUnitName" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="AdditionalInformationType">
        <xs:sequence>
            <xs:element name="text" type="xs:string" minOccurs="0"/> <!-- Narrative block! -->
            <xs:element name="desiredDateForPerformance" type="DesiredDateForPerformanceType" minOccurs="0"/>
            <xs:element name="desiredRequestRecipient" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="administrativeInformation" type="xs:string" minOccurs="0" />
            <xs:element name="interpreterRequirement" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AwarenessInformationType">
        <xs:sequence>
            <xs:element name="text" type="xs:string" />
            <xs:element name="clinicalInformation" type="DescriptionType" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>    
        
    <xs:complexType name="QuestionFormulationType">
        <xs:sequence>
            <xs:element name="id" type="gcda:ii"/>
            <xs:element name="text" type="xs:string" />
            <xs:element name="desiredAction" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="clinicalInformation" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OutcomeType">
        <xs:sequence>
            <xs:element name="text" type="xs:string" />
            <xs:element name="clinicalInformation" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="accomplishedAction" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="DesiredDateForPerformanceType">
        <xs:attribute name="start">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\d+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="end">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\d+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType> 
    
    <xs:complexType name="DescriptionType">
        <xs:sequence>
            <xs:element name="id" type="gcda:ii"/>
            <xs:element name="condition" type="gcda:ii" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/testcase_02_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- SLL eRemiss testcase 2 -->
<request xmlns:gcda="AlschulerAssociates::GreenCDA" xmlns:gcdan="AlschulerAssociates::GreenCDA::Narrative" xmlns="urn:riv:clinicalprocess:requestworkflow:request"
         xsi:schemaLocation="urn:riv:clinicalprocess:requestworkflow:request remiss.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
             
    <requestId root="1.2.752.129.2.1.2.1" extension="testfall2"/>
    <typeOfRequest code="4" codeSystem="1.2.752.129.2.2.2.24"/>
    <versionTimeStamp value="201203121636"/>
    <versionNumber>1</versionNumber>
    <reasonForVersion>
        <typeOfReason code="VR" codeSystem="1.2.752.97.3.2.8.5"/>
        <text>Remissen skickas vidare till er då patienten är listad hos er.</text>
    </reasonForVersion>
    
    <!-- Patient -->
    <patient>
        <personId root="1.2.752.97.3.1.2" extension="197907179191"/>
        <address>
            <careOf>Mikkonen</careOf>
            <streetName1>Astrakangatan 14</streetName1>
            <postalCode>16565</postalCode>
            <postalCity>Hässelby</postalCity>
        </address>
        <telecom>
            <typeOfTelecom code="MC" codeSystem="1.2.752.129.2.2.1.30"/>
            <number>+46706123123</number>
        </telecom>
        <!-- Efternamn/mellannamn/tilltalsnamn/förnamn -->
        <name>Testsson//Vårdtest</name>
        <gender code="1" codeSystem="1.2.752.129.2.2.1.1"/>
        <dateOfBirth value="19790917"/>
    </patient>

    <author>
        <dateOfRequest value="20120312"/>
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <name>Elin Ek</name>
        </staff>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8"/>
        <staffOrganisation>
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Avd 33, Medicinkliniken, Capio S:t Görans sjukhus</careUnitName>
        </staffOrganisation>
        <legalAuthenticator>  
            <timeOfSigning value="201203121344"/>
            <signature>
                <id root="1.2.752.129.2.1.4.1" extension="HSAid" />
                <name>Elin EK, AT-läkare</name>
            </signature>
        </legalAuthenticator>
    </author>
    
    <recipient>
        <organisation>
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Råcksta-Vällingby närvårdsmottagning</careUnitName>
        </organisation>
    </recipient>
    
    <!-- Not used in this testcase
    <participant>
    </participant>
    -->
    
    <!-- Remissförmedlare -->
    <intermediary>
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <name>Jonas Dahl</name>
        </staff>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8" />
        <staffOrganisation>            
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Hässelby vårdcentral</careUnitName>
        </staffOrganisation>
    </intermediary>
    
    <additionalInformation>
        <desiredRequestRecipient>Vederbörande husläkare</desiredRequestRecipient>
        <interpreterRequirement>Behöver finsk tolk.</interpreterRequirement>
    </additionalInformation>
    
    <awarenessInformation>
        <text>Har hepatit C.</text>
    </awarenessInformation>
    
    <questionFormulation>
        <id root="1.2.752.129.2.1.2.1" extension="2"/>
        <text>Diabetes?</text>
        <clinicalInformation>
            <id root="1.2.752.129.2.1.2.1" extension="2"/>
            <description>33-årig blandmissbrukande man som inkom 11/3 pga centrala bröstsmärtor. Patienten har vårdats inneliggande under ett dygn och hjärtinfarkt har uteslutits. Smärtorna bedöms som muskuloskelettala. Under vårdtiden har förhöjda blodsockervärden uppmätts vid flera tillfällen som högst 10,8. Patienten har ingen känd diabetes. Tacksam för uppföljning av patientens förhöjda blodsockervärden.

                Vänliga hälsningar
                Elin EK
                AT-läkare
            </description>
        </clinicalInformation>
    </questionFormulation>
</request>

=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/testcase_08_requestOutcome.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- SLL eRemiss testcase 8-->
<requestOutcome xmlns:gcda="AlschulerAssociates::GreenCDA" xmlns:gcdan="AlschulerAssociates::GreenCDA::Narrative" xmlns="urn:riv:clinicalprocess:requestworkflow:request"
                xsi:schemaLocation="urn:riv:clinicalprocess:requestworkflow:request remiss.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <requestId root="1.2.752.129.2.1.2.1" extension="testfall8"/>
    <requestOutcomeId root="1.2.752.129.2.1.2.1" extension="testfall7"/>
    <typeOfRequestOutcome code="RB" codeSystem="1.2.752.97.3.2.8.6"/>
    <versionTimeStamp value="201203011636"/>
    <versionNumber>1</versionNumber>
    
    <author>
        <dateOfRequest value="20120315"/>
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <name>Jonas Dahl</name>
        </staff>
        <staffOrganisation>
            <careUnitId root="1.2.752.97.3.1.1" extension="HSAid"/>
            <careUnitName>Hässelby vårdcentral</careUnitName>
        </staffOrganisation>
        <legalAuthenticator>
            <timeOfSigning value="201204301233"/>
            <signature>
                <id root="1.2.752.129.2.1.4.1" extension="HSA-id for signer"/>
                <name>Jonas Dahl</name>
            </signature>
        </legalAuthenticator>
    </author>
        
    <recipient>
        <organisation>
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSA-id for recipient of reuqest"/>
            <careUnitName>Capio S:t Görans sjukhus, Ortopedmottagningen</careUnitName>
        </organisation>
    </recipient>
    

    <outcome>
    </outcome>
</requestOutcome>

=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/testcase_01_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<request xmlns:gcda="AlschulerAssociates::GreenCDA" xmlns:gcdan="AlschulerAssociates::GreenCDA::Narrative" xmlns="urn:riv:clinicalprocess:requestworkflow:request"
         xsi:schemaLocation="urn:riv:clinicalprocess:requestworkflow:request remiss.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
             
    <requestId root="1.2.752.129.2.1.2.1" extension="abc123"/>
    <typeOfRequest code="4" codeSystem="1.2.752.129.2.2.2.24"/>
    <versionTimeStamp value="201203121636"/>
    <versionNumber>1</versionNumber>
    <reasonForVersion>
        <typeOfReason code="NR" codeSystem="1.2.752.97.3.2.8.5"/>
    </reasonForVersion>

    <patient>
        <personId root="1.2.752.97.3.1.2" extension="197907179191"/>
        <address>
            <careOf>Mikkonen</careOf>
            <streetName1>Astrakangatan 14</streetName1>
            <postalCode>16565</postalCode>
            <postalCity>Hässelby</postalCity>
        </address>
        <telecom>
            <typeOfTelecom code="MC" codeSystem="1.2.752.129.2.2.1.30"/>
            <number>+46706123123</number>
        </telecom>
        <!-- Efternamn/mellannamn/tilltalsnamn/förnamn -->
        <name>Testsson/Vårdtest//</name>
        <gender code="1" codeSystem="1.2.752.129.2.2.1.1"/>
        <dateOfBirth value="19790917"/>
    </patient>

    <author>
        <!-- Maps to clinicalDocument/author/time -->                               
        <dateOfRequest value="20120312"/>
        <!-- No mapping for clinicalDocument/author/assignedAuthor -->                               
        <staff>
           <!-- Maps to clinicalDocument/author/assignedAuthor/id --> 
            <id root="1.2.752.129.2.1.4.1" extension="HSAid Remittent"/>
            <!-- Maps to clinicalDocument/author/assignedAuthor/assignedPerson/name -->                               
            <name>Elin Ek</name>
        </staff>
        <!-- Maps to clinicalDocument/author/assignedAuthor/code -->                               
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8"/>
        <staffOrganisation>
            <!-- Maps to clinicalDocument/author/assignedAuthor/representedOrganization/id -->                                     
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSA-id for RT organization"/>
            <!-- Maps to clinicalDocument/author/assignedAuthor/representedOrganization/name -->                                     
            <careUnitName>Avd 33, Medicinkliniken, Capio S:t Görans sjukhus</careUnitName>
        </staffOrganisation>
        
        <legalAuthenticator>
            <timeOfSigning value="201203121122"/>
            <signature>
                <id root="1.2.752.129.2.1.4.1" extension="HSA-id for signer" />
                <name>Elin Ek</name>
            </signature>
        </legalAuthenticator>
    </author>

    <recipient>
        <organisation>
            <!-- Maps to clinicalDocument/informationRecipient/receivedOrganization/id -->                                     
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSA-id for recipient organization"/>
            <!-- Maps to clinicalDocument/informationRecipient/receivedOrganization/name -->                                     
            <careUnitName>Hasselby vårdcentral</careUnitName>
        </organisation>
    </recipient>

    <additionalInformation>
        <desiredDateForPerformance start="20120501" end="20120601" />
        <desiredRequestRecipient>Vederbörande husläkare</desiredRequestRecipient>                
        <interpreterRequirement>Behöver finsk tolk.</interpreterRequirement>
    </additionalInformation>

    <awarenessInformation>
        <text>Har hepatit C.</text>
	<!-- <clinicalInformation /> -->
    </awarenessInformation>

    <questionFormulation>
        <id root="1.2.752.129.2.1.2.1" extension="1"/>
        <text>Diabetes?</text>
        <!-- <desiredAction/> -->
        <clinicalInformation>
            <id root="1.2.752.129.2.1.2.1" extension="1"/>
            <description>33-årig blandmissbrukande man som inkom 11/3 pga centrala bröstsmärtor. Patienten har vårdats inneliggande under ett dygn och hjärtinfarkt har uteslutits. Smärtorna bedöms som muskuloskelettala. Under vårdtiden har förhöjda blodsockervärden uppmätts vid flera tillfällen som högst 10,8. Patienten har ingen känd diabetes. Tacksam för uppföljning av patientens förhöjda blodsockervärden.

                Vänliga hälsningar
                Elin EK
                AT-läkare
            </description>
        </clinicalInformation>
    </questionFormulation>
</request>

=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/testcase_06_requestOutcome.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- SLL eRemiss testcase 6, RB -->
<requestOutcome xmlns:gcda="AlschulerAssociates::GreenCDA" xmlns:gcdan="AlschulerAssociates::GreenCDA::Narrative" xmlns="urn:riv:clinicalprocess:requestworkflow:request"
                xsi:schemaLocation="urn:riv:clinicalprocess:requestworkflow:request remiss.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
             
    <requestId root="1.2.752.129.2.1.2.1" extension="testfall8"/>
    <requestOutcomeId root="1.2.752.129.2.1.2.1" extension="testfall7"/>
    <typeOfRequestOutcome code="RB" codeSystem="1.2.752.97.3.2.8.6"/>
    <versionTimeStamp value="201203011636"/>
    <versionNumber>1</versionNumber>
    
    <author>
        <dateOfRequest value="20120318"/>
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <name>Lena Andersson</name>
        </staff>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8" />
        <staffOrganisation>
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Capio S:t Görans sjukhus, Ortopedmottagningen</careUnitName>
        </staffOrganisation>
            
        <legalAuthenticator>
            <timeOfSigning value="201203151233"/>
            <signature>
                <id root="1.2.752.129.2.1.4.1" extension="HSA-id for signer"/>
                <name>Lena Andersson</name>
            </signature>
        </legalAuthenticator>
    </author>
    
    <recipient>
        <staff>
            <id root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <name>Jonas Dahl</name>
        </staff>
        <organisation>
            <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
            <careUnitName>Hässelby vårdcentral</careUnitName>
        </organisation>
    </recipient>
    
    <outcome>
        <text>Vi har mottagit remissen.
            Pat är satt på väntelista och beräknas att kallas inom 10 veckor.
        </text>
    </outcome>
</requestOutcome>

=== merikan/skltpservices/ServiceInteractions/local/clinicalprocess/requestworkflow/trunk/Schema/schemas/core_components/testcase_07_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- SLL eRemiss testcase 7 -->
<request xmlns:gcda="AlschulerAssociates::GreenCDA" xmlns:gcdan="AlschulerAssociates::GreenCDA::Narrative" xmlns="urn:riv:clinicalprocess:requestworkflow:request"
         xsi:schemaLocation="urn:riv:clinicalprocess:requestworkflow:request remiss.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <requestId root="1.2.752.129.2.1.2.1" extension="testfall7"/>
    <typeOfRequest code="4" codeSystem="1.2.752.129.2.2.2.24"/>
    <versionTimeStamp value="201203011636"/>
    <versionNumber>1</versionNumber>
    
    <reasonForVersion>
        <typeOfReason code="NR" displayName="Ny request" codeSystem="1.2.752.97.3.2.8.5"/>        
    </reasonForVersion>

    <patient>
        <personId root="1.2.752.97.3.1.2" extension="197907179191"/>
        <address>
            <careOf>Mikkonen</careOf>	
            <streetName1>Astrakangatan 14</streetName1>
            <streetName2>Uppgång C</streetName2>
            <streetName3>Lgh 0014</streetName3>
            <postalCode>16565</postalCode>
            <postalCity>Hässelby</postalCity>
        </address>
        <telecom>
            <typeOfTelecom code="H" codeSystem="1.2.752.129.2.2.1.30"/>
            <number>+468123123</number>
        </telecom>
        <telecom>
            <typeOfTelecom code="MC" codeSystem="1.2.752.129.2.2.1.30"/>
            <number>+46706123123</number>
        </telecom>
        <!-- Efternamn/mellannamn/tilltalsnamn/förnamn -->
        <name>Testsson/Anders/Vårdtest/Vårdtest</name>
        <gender code="1" codeSystem="1.2.752.129.2.2.1.1"/>
        <dateOfBirth value="19790917"/>

    </patient>
    
    <author>
        <dateOfRequest value="20120315"/>
        
        <legalAuthenticator>
            <timeOfSigning value="201203151233"/>
            <signature>
                <id />
                <name>Jonas Dahl, Distriktsläkare</name> 
            </signature>
        </legalAuthenticator>
    </author>
    
    <recipient>
       <!-- <requestrolltyp code="SM" displayName="Svarsmottagare" codeSystem="1.2.752.97.3.2.8.4"/> -->
        <id root="1.2.752.97.3.1.1" extension="HSAid"/>
        <name>Jonas Dahl</name>
        <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
        <vardgivarid root="1.2.752.129.2.1.4.1" extension="HSAid"/>
        <lansid root="1.2.752.129.2.1.4.1" extension="HSAid"/>
        <careUnitName>Hässelby vårdcentral</careUnitName>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8" />
    </recipient>
    
    <additionalInformation>
        <text>Patienten är bortrest utomlands 2012-03-15 – 2012-04-14 och kan därför kallas tidigast 2012-04-15</text>
        <desiredDateForPerformance start="20120415" end="20120831"/>
        <desiredRequestRecipient>Specialistläkare inom ortopedi</desiredRequestRecipient>
        <interpreterRequirement>Behöver finsk tolk.</interpreterRequirement>
    </additionalInformation>
    
    <awarenessInformation>
        <text>Har hepatit C.</text>
    </awarenessInformation>
    
    <involverarroller>
        <rollinstansid root="1.2.752.97.x.x.x.x" extension="123"/>
        <requestrolltyp code="RB" displayName="Remissbedömare" codeSystem="1.2.752.97.3.2.8.4"/>
        <name>Robert Larsson</name>
        <careUnitId root="1.2.752.129.2.1.4.1" extension="HSAid"/>
        <vardgivarid root="1.2.752.129.2.1.4.1" extension="HSAid"/>
        <lansid root="1.2.752.129.2.1.4.1" extension="HSAid"/>
        <careUnitName>Capio S:t Görans sjukhus, Ortopedmottagningen</careUnitName>
        <typeOfStaff code="LK" codeSystem="1.2.752.97.3.2.8.8" />
    </involverarroller>

    <questionFormulation>
        <id root="1.2.752.129.2.1.2.1" extension="7"/>
        <text>Meniskskada? Korsbandsskada?</text>
        <clinicalInformation>
            <id root="1.2.752.129.2.1.2.1" extension="7"/>
            <!-- <tillstand code="S83.6" displayName="Tillstånd XXX" codeSystem="1.2.752.97.x.x.x.x"/> -->
            <description>33-årig blandmissbrukande man som ramlade omkring 1 februari i berusat tillstånd och på något sätt skadat höger knä. Ej sökt vård. Sedan dess har patienten haft intermittent svullnad av höger knä och låsningsfenomen. I status noteras måttlig hydrops, kraftig smärta vid meniskprovokationstest och misstänkt främre draglåda. Röntgenundersökning har inte visat något patologiskt. Har ej genomgått MR. Tacksam för bedömning och ställningstagande till artroskopi.

                Hälsningar
                Jonas Dahl
                Distriktsläkare
            </description>
            <!--
            <atgarder>
                <atgardid root="1.2.752.97.x.x.x.x" extension="123"/>
                <atgardtyp code="NGA11" displayName="Åtgärdskod XXX" codeSystem="1.2.752.97.x.x.x.x"/>
                <atgarddescription>Artroskopi höger knä</atgarddescription>
            </atgarder>
            -->
        </clinicalInformation>
    </questionFormulation>
</request>
